BS5_SoundPresetRegistryConfig {
 m_aPresets {
  BS5_SoundPresetConfigEntry "{C881178130F85B02}" {
   m_sId "vanilla"
   m_sDisplayName "Vanilla"
   m_fEchoVolume 0.5
   m_fSlapbackVolume 0.45
   m_fSlapbackCloseVolume 0.45
  }
  BS5_SoundPresetConfigEntry "{C881178130F85B03}" {
   m_sId "bettersounds_v4"
   m_sDisplayName "BetterSoundsV4"
   m_fEchoVolume 0.9
   m_fSlapbackVolume 0.77
   m_fSlapbackCloseVolume 0.77
  }
  BS5_SoundPresetConfigEntry "{C881178130F85B04}" {
   m_sId "bettersounds_v5"
   m_sDisplayName "BetterSoundsV5"
   m_fEchoVolume 0.8
   m_fSlapbackVolume 0.6
   m_fSlapbackCloseVolume 0.6
  }
  BS5_SoundPresetConfigEntry "{C881178130F85B05}" {
   m_sId "lunacy_audio"
   m_sDisplayName "LunacyAudio"
   m_fEchoVolume 0.7
   m_fSlapbackVolume 0.5
   m_fSlapbackCloseVolume 0.5
  }
 }
}
